### ISSUE TITLE
Find suitable logo for the site

### ISSUE THREAD

**Issue by ZvikaNaorCohen** [ZvikaNaorCohen/StreamersMarketplace#1]

**Comment by ZvikaNaorCohen** [comment]
![sales (1)](https://user-images.githubusercontent.com/57681792/232226439-fc4f9195-593e-4967-86fc-08060a918b9c.png)
![sales](https://user-images.githubusercontent.com/57681792/232226441-285b5658-79bc-4a3c-834a-07afc09000fe.png)
What do you guys think? @EliranGooner @MatanCohenMC

**Comment by EliranGooner** [comment]
Cool! I think that's the one
