### ISSUE TITLE
Navbar is "eating" the components below it, and I can't figure how to take them components down.

### ISSUE THREAD

**Issue by ZvikaNaorCohen** [ZvikaNaorCohen/StreamersMarketplace#23]
it looks like:
![image](https://user-images.githubusercontent.com/57681792/232223092-ec7f969a-9653-4c87-90d5-9ea35e431957.png)

instead of something like:
![image](https://user-images.githubusercontent.com/57681792/232223122-c308d5df-8fc9-4c06-a51a-02723856825e.png)
(But with the text smaller and not touching the navbar)

**Comment by ZvikaNaorCohen** [comment]
Right now navbar is not fixed, would be fixed when I will work on this issue.

**Comment by MatanCohenMC** [comment]
Done :)
