### ISSUE TITLE
After logging with Google - if user has no picture - something weird would appear.

### ISSUE THREAD

**Issue by ZvikaNaorCohen** [ZvikaNaorCohen/StreamersMarketplace#30]
Few options:
1. We won't include a photo in the navbar google login.
2. We'll add "if-else": If there is a photo, add it. If not, add something else (remove photo / use a default one)

**Comment by MatanCohenMC** [comment]
For me even though I deleted my profile pic, the pic in the navbar is the letter "M" as seen on Gmail.
I added an "alt" option for default profile pic.

**Comment by MatanCohenMC** [comment]
Checked with noa's account which she doesn't have a profile picture
